url: https://jonasman.github.com
baseurl: /teamsite

# Site settings
title: T Team
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: João Nunes
  pic: 1
  position: Co-founder - Lead iOS developer and Product Manager
  description: Passionate about iOS and creating great products. João works at Zalando where he has aquired most of his experience.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Luís Ramalho
  pic: 2
  position: Co-founder - Engineering Manager
  description: Computer Science graduate and Engineering Business Management postgraduate Luís works at Smartly.io where he is using his business and technical skills to help companies grow.
  social:
    - title: twitter
      url: https://twitter.com/luisramalho
    - title: stack-overflow
      url: https://stackoverflow.com/users/848250/lu%c3%ads-ramalho
    - title: linkedin
      url: https://www.linkedin.com/in/luismanuelramalho/

- name: Javier Martinez
  pic: 3
  position: Senior Product Manager
  description: Javier has been working for top e-commerce compannies like Zalando and now he is currently at Amazon. Javier excells at Product managment, scrum master and has very strong communications skills.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: João Silva
  pic: 4
  position: Lead Java developer
  description: João is a top developer working at Cern. His passion for quality lead him to be a lead developer in his team. João is experienced in ETH Blockchain and develops 
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Martin Talvari
  pic: 5
  position: Lead Strategy, Event Manager
  description: A passionate communicator with good strategic eye. Martin worked for Slush and Myriad creating top conferences.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Mário Dourado
  pic: 6
  position: Lead Business Intelligence
  description: Developer at his heart, Mario also carries enterprenourship skills from previous startup. Mário is great at communication too.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

- name: Nuno Alexandre
  pic: 7
  position: Lead Sales
  description: Nuno started his career as a IT specialist but soon realized managment was his passion. Nuno works at Cominfo as a top sales advisor. Nuno excels at communication and negotiation.
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line:
  - line: Europe

# Build settings
markdown: kramdown
permalink: pretty
